<h1 style="color:white;background-color:red;text-align:center;font-size:350%;font-family:calibri">Chirag Agarwal</h1><h2 style="color:white;background-color:red;text-align:center;font-size:250%;font-family:calibri">18EARIT015</h2>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pickle
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
import seaborn as sns

### Step-1 Load Data

In [3]:
df = sns.load_dataset('mpg')

In [4]:
df.shape

(398, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [6]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [7]:
target = df['mpg']

In [8]:
for col in df.columns[:-2]:
    print(f"{col:>15} Corr Coeff: {np.corrcoef(df[col], target)[0][1]}")

            mpg Corr Coeff: 1.0
      cylinders Corr Coeff: -0.7753962854205543
   displacement Corr Coeff: -0.8042028248058979
     horsepower Corr Coeff: nan
         weight Corr Coeff: -0.8317409332443351
   acceleration Corr Coeff: 0.42028891210165065
     model_year Corr Coeff: 0.5792671330833097


In [9]:
df['horsepower'].isnull().value_counts()

False    392
True       6
Name: horsepower, dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
df['horsepower'].isnull().value_counts()

False    392
Name: horsepower, dtype: int64

In [12]:
features = df[['cylinders','displacement','horsepower','weight']]

In [13]:
features.head()

cylinders  displacement  horsepower  weight
0          8         307.0       130.0    3504
1          8         350.0       165.0    3693
2          8         318.0       150.0    3436
3          8         304.0       150.0    3433
4          8         302.0       140.0    3449

In [14]:
features.isna().sum()

cylinders       0
displacement    0
horsepower      0
weight          0
dtype: int64

In [18]:
target = df['mpg']

In [20]:
target.value_counts()

13.0    20
14.0    19
18.0    17
15.0    16
26.0    14
        ..
30.7     1
31.9     1
44.0     1
28.8     1
27.4     1
Name: mpg, Length: 127, dtype: int64

In [15]:
features.shape

(392, 4)

In [16]:
df.shape

(392, 9)

### Step-2 and 3 Split Data and selecting best observations

In [21]:
X_train, X_test, y_train, y_test = train_test_split(features, target)

In [22]:
X_train.shape

(294, 4)

In [23]:
y_train.shape

(294,)

In [25]:
X_test.shape

(98, 4)

In [26]:
98/392*100  # means 25% are testing values

25.0

### Step-4  Training the model

In [27]:
model=LinearRegression()

In [28]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [29]:
model.coef_

array([-0.33510054, -0.00274268, -0.03137103, -0.00538003])

In [30]:
model.intercept_

44.992186866210254

### Step-5 Evaluation of model

In [31]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [32]:
predict = model.predict(X_test)

In [33]:
predict[:5]

array([26.56896635, 29.21778571, 30.93751826, 18.53541224, 27.23893673])

In [36]:
y_test.to_numpy()[:5]

array([28. , 25. , 38.1, 17. , 25. ])

In [37]:
mse = mean_squared_error(y_test, predict)
print(f"MSE: {mse:.2f}")
print(f"RMSE: {np.sqrt(mse):.2f}")

MSE: 19.47
RMSE: 4.41


In [38]:
acc = r2_score(y_test, predict)
print(f"Accuracy: {acc*100:.2f}")

Accuracy: 71.67


### Normalising it

In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
scale_model = StandardScaler()

In [42]:
scaled_features = scale_model.fit_transform(features)

In [44]:
scaled_features = pd.DataFrame(scaled_features, columns=['cylinders','displacement','horsepower','weight'])

In [45]:
scaled_features[:5]

cylinders  displacement  horsepower    weight
0   1.483947      1.077290    0.664133  0.620540
1   1.483947      1.488732    1.574594  0.843334
2   1.483947      1.182542    1.184397  0.540382
3   1.483947      1.048584    1.184397  0.536845
4   1.483947      1.029447    0.924265  0.555706

In [46]:
new_model = LinearRegression()

In [47]:
xtrain, xtest, ytrain, ytest = train_test_split(scaled_features, target)

In [48]:
new_model.fit(xtrain, ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [49]:
pred = new_model.predict(xtest)

In [50]:
r2_score(ytest, pred)

0.7850551704881739

In [51]:
fp=open('mileage.pkl','wb')
pickle.dump(new_model,fp)

In [52]:
fp.close()

<h2 style="color:white;background-color:red;text-align:center;font-size:250%;font-family:calibri">Thankyou!!!</h2>